spring:
  profiles:
    group:
      "local": "local,logging_local"
      "dev": "dev,logging_dev"
      "prod": "prod,logging_daily"
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
app:
#  filePath: /Users/geumjiun/Documents/gogopay/upload
  filePath: /home/develop2/theCreditable/CMS/resource
