#spring.datasource.url=jdbc:mariadb://localhost:3306/querydsl
#spring.datasource.username=query
#spring.datasource.password=0814
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
  
  
# true -> You can see the SQL statement sent by JPA
#spring.jpa.show-sql=true
  #logging.level.org.hibernate.type.descriptor.sql=trace
#spring.jpa.properties.hibernate.format_sql=true
  
  # create -> JPA can create a table,
  # none -> no create, change attribute -> update
#spring.jpa.hibernate.ddl-auto=none

#spring.jpa.properties.hibernate.default_batch_fetch_size=100

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    username: query
    password: 0814
    driver-class-name: org.mariadb.jdbc.Driver

    spring-doc:
      swagger-ui:
        #http://localhost:8080/swagger-ui/#
        path: /swagger-ui.html
        displayRequestDuration: true
        gorups-order: DESC


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        use_sql_comments: true


logging.level:
  org.hibernate.SQL: debug
  #trace =